### ISSUE TITLE
EDK to KEK, HMAC key

### ISSUE THREAD

**Issue by rgw810** [laginimaineb/android_fde_bruteforce#2]
I downloaded this program in hopes of unlocking a Motorola phone using Android 5.0, looking over the information from here [https://github.com/hashcat/hashcat/issues/411](url) I downloaded the footer.bin and was looking at the KEK key and was wondering how you were able to get this as I dont see it in the footer.bin file or the HMAC Key.

I have the EDK of my encrypted phone and am trying to convert this over to a KEK and this info would really help me out along with the HMAC information.

Appreciate the help

**Comment by laginimaineb** [comment]
See the blog post for more information:
http://bits-please.blogspot.co.uk/2016/06/extracting-qualcomms-keymaster-keys.html

On Mar 2, 2017 1:43 PM, "rgw810" <notifications@github.com> wrote:

I downloaded this program in hopes of unlocking a Motorola phone using
Android 5.0, looking over the information from here
https://github.com/hashcat/hashcat/issues/411 <http://url> I downloaded the
footer.bin and was looking at the KEK key and was wondering how you were
able to get this as I dont see it in the footer.bin file or the HMAC Key.

I have the EDK of my encrypted phone and am trying to convert this over to
a KEK and this info would really help me out along with the HMAC
information.

Appreciate the help

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/laginimaineb/android_fde_bruteforce/issues/2>, or mute
the thread

**Comment by rgw810** [comment]
great article! I think I know the answer to this but, will this work on a dd or bin image of the device or does the phone itself need to be injected with the code

**Comment by laginimaineb** [comment]
Thank you! You'll need to run the exploits themselves on the phone first to
extract the KEK.

On Mar 2, 2017 6:40 PM, "rgw810" <notifications@github.com> wrote:

great article! I think I know the answer to this but, will this work on a
dd or bin image of the device or does the phone itself need to be injected
with the code

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/laginimaineb/android_fde_bruteforce/issues/2#issuecomment-283740648>,
or mute the thread
